package com.selenium;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;


public class Mini_Project_2 {
	public static void main(String[] args) throws InterruptedException, IOException {
		System.setProperty("webdriver.edge.driver","C:\\Users\\acer\\eclipse-workspace\\Selenium\\ed driver\\msedgedriver.exe");
		WebDriver driver = new EdgeDriver();
		driver.get("http://automationpractice.com/index.php");
		Thread.sleep(5000);
		driver.manage().window().maximize();
		Thread.sleep(5000);
		WebElement w1 = driver.findElement(By.xpath("//a[@class='login']"));
		w1.click();
		Thread.sleep(5000);
		/*WebElement w2 = driver.findElement(By.xpath("//input[@id='email_create']"));
		w2.sendKeys("kkd797@gmail.com");
		Thread.sleep(5000);
		WebElement w3 = driver.findElement(By.xpath("//button[@id='SubmitCreate']"));
		w3.click();
		Thread.sleep(5000);
		WebElement w4 = driver.findElement(By.name("id_gender"));
		w4.click();
		Thread.sleep(5000);
		WebElement w5 = driver.findElement(By.name("customer_firstname"));
		w5.sendKeys("Ashwin");
		Thread.sleep(5000);
		WebElement w6 = driver.findElement(By.name("customer_lastname"));
		w6.sendKeys("kumar");
		Thread.sleep(5000);
		WebElement w7 = driver.findElement(By.name("passwd"));
		w7.sendKeys("saibaba");
		Thread.sleep(5000);
		WebElement w8 = driver.findElement(By.name("days"));
		Select s = new Select(w8);
		s.selectByValue("15");
		Thread.sleep(5000);
		WebElement w9 = driver.findElement(By.name("months"));
		Select s1 = new Select(w9);
		s1.selectByValue("10");
		Thread.sleep(5000);
		WebElement w10 = driver.findElement(By.name("years"));
		Select s2 = new Select(w10);
		s2.selectByValue("1994");
		Thread.sleep(5000);
		WebElement w11 = driver.findElement(By.name("company"));
		w11.sendKeys("xyz pvt ltd");
		Thread.sleep(5000);
		WebElement w12 = driver.findElement(By.name("address1"));
		w12.sendKeys("6 garden view 3rd st vetri nagar");
		Thread.sleep(5000);
		WebElement w13 = driver.findElement(By.name("address2"));
		w13.sendKeys("Avadi ch -54");
		Thread.sleep(5000);
		WebElement w14 = driver.findElement(By.name("city"));
		w14.sendKeys("Avadi");
		Thread.sleep(5000);
		WebElement w15 = driver.findElement(By.xpath("//select[@name ='id_state']"));
		Select s3 = new Select(w15);
		s3.selectByIndex(5);
		Thread.sleep(5000);
		WebElement w16 = driver.findElement(By.name("postcode"));
		w16.sendKeys("60000");
		Thread.sleep(5000);
		WebElement w17 = driver.findElement(By.name("other"));
		w17.sendKeys("Na");
		Thread.sleep(5000);
		WebElement w18 = driver.findElement(By.name("phone"));
		w18.sendKeys("9515612356");
		Thread.sleep(5000);
		WebElement w19 = driver.findElement(By.name("phone_mobile"));
		w19.sendKeys("9561231456");
		Thread.sleep(5000);
		WebElement w20 = driver.findElement(By.name("submitAccount"));
		w20.click();
		Thread.sleep(5000);*/
		WebElement w2 = driver.findElement(By.name("email"));
		w2.sendKeys("ashnaveenw5@gmail.com");
		Thread.sleep(5000);
		WebElement w3 = driver.findElement(By.name("passwd"));
		w3.sendKeys("saibaba");
		Thread.sleep(5000);
		WebElement w4 = driver.findElement(By.name("SubmitLogin"));
		w4.click();
		Thread.sleep(5000);
		WebElement w5 = driver.findElement(By.xpath("//a[@title='Women']"));
		w5.click();
		Thread.sleep(5000);
		WebElement w6 = driver.findElement(By.xpath("//*[@id=\"center_column\"]/ul/li[1]/div/div[2]/h5/a"));
		w6.click();
		Thread.sleep(5000);
		WebElement w7 = driver.findElement(By.name("Submit"));
		w7.click();
		Thread.sleep(5000);
		WebElement w8 = driver.findElement(By.xpath("//a[@title='Proceed to checkout']"));
		w8.click();
		Thread.sleep(5000);
		WebElement w9 = driver.findElement(By.xpath("//*[@id=\"center_column\"]/p[2]/a[1]"));
		w9.click();
		WebElement w10 = driver.findElement(By.name("processAddress"));
		w10.click();
		Thread.sleep(5000);
		WebElement w11 = driver.findElement(By.name("cgv"));
		w11.click();
		Thread.sleep(5000);
		WebElement w12 = driver.findElement(By.name("processCarrier"));
		w12.click();
		Thread.sleep(5000);
		WebElement w13 = driver.findElement(By.xpath("//a[@title='Pay by bank wire']"));
		w13.click();
		Thread.sleep(5000);
		WebElement w14 = driver.findElement(By.xpath("//*[@id=\"cart_navigation\"]/button"));
		w14.click();
		Thread.sleep(5000);
		JavascriptExecutor ex =(JavascriptExecutor) driver;
		Thread.sleep(5000);
		ex.executeScript("window.scroll(0,500)", "");
		Thread.sleep(15000);
		TakesScreenshot ts = (TakesScreenshot) driver;
		File source = ts.getScreenshotAs(OutputType.FILE);
		File des = new File("C:\\Users\\acer\\eclipse-workspace\\Selenium\\Screenshot\\miniproject2.png");
		FileUtils.copyFile(source, des);
		Thread.sleep(5000);
		driver.close();
		}
}
