package com.selenium;
import java.io.File;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.support.ui.Select;
public class Mini_Project {
public static void main(String[] args) throws InterruptedException, Throwable {
	System.setProperty("webdriver.edge.driver","C:\\Users\\acer\\eclipse-workspace\\Selenium\\ed driver\\msedgedriver.exe");
    WebDriver driver = new EdgeDriver();
    driver.get("http://adactinhotelapp.com/index.php");
    driver.manage().window().maximize();
    Thread.sleep(5000);
    WebElement username = driver.findElement(By.name("username"));
    username.sendKeys("Navs4060");
    Thread.sleep(5000);
    WebElement password = driver.findElement(By.name("password"));
    password.sendKeys("baba55");
    Thread.sleep(5000);
    WebElement login = driver.findElement(By.name("login"));
    login.click();
    Thread.sleep(5000);
    WebElement w = driver.findElement(By.name("location"));
    Select s = new Select(w);
    s.selectByIndex(5);
    Thread.sleep(5000);
    WebElement w1 =driver.findElement(By.name("hotels"));
    Select s1 = new Select(w1);
    s1.selectByIndex(3);
    Thread.sleep(5000);
    WebElement w2 = driver.findElement(By.name("room_type"));
    Select s2 = new Select(w2);
    s2.selectByIndex(4);
    Thread.sleep(5000);
    WebElement w3 =driver.findElement(By.name("room_nos"));
    Select s3 = new Select(w3);
    s3.selectByIndex(5);
    Thread.sleep(5000);
    WebElement w4 = driver.findElement(By.name("datepick_in"));
    w4.clear();
    Thread.sleep(5000);
    w4.sendKeys("06/05/2022");
    Thread.sleep(5000);
    WebElement w5 = driver.findElement(By.name("datepick_out"));
    w5.clear();
    Thread.sleep(5000);
    w5.sendKeys("07/05/2022");
    Thread.sleep(5000);
    WebElement w6 = driver.findElement(By.name("adult_room"));
    Select s4 = new Select(w6);
    s4.selectByIndex(2);
    Thread.sleep(5000);
    WebElement w7 = driver.findElement(By.name("child_room"));
    Select s5 = new Select(w7);
    s5.selectByIndex(2);
    Thread.sleep(5000);
    WebElement w8 =driver.findElement(By.name("Submit"));
    w8.click();
    Thread.sleep(5000);
    WebElement w9 = driver.findElement(By.name("radiobutton_0"));
    w9.click();
    Thread.sleep(5000);
    WebElement w10 = driver.findElement(By.name("continue"));
    w10.click();
    Thread.sleep(5000);
    WebElement w11 = driver.findElement(By.name("first_name"));
    w11.sendKeys("Ashwin");
    Thread.sleep(5000);
    WebElement w12 = driver.findElement(By.name("last_name"));
    w12.sendKeys("kumar");
    Thread.sleep(5000);
    WebElement w13 = driver.findElement(By.name("address"));
    w13.sendKeys("6,vivek garden 3rd st vetri nagar, avadi ch-54 ");
    Thread.sleep(5000);
    WebElement w14 = driver.findElement(By.name("cc_num"));
    w14.sendKeys("1234567810111213");
    Thread.sleep(5000);
    WebElement w15 = driver.findElement(By.name("cc_type"));
    Select s6 = new Select(w15);
    s6.selectByIndex(3);
    Thread.sleep(5000);
    WebElement w16 = driver.findElement(By.name("cc_exp_month"));
    Select s7 = new Select(w16);
    s7.selectByIndex(10);
    Thread.sleep(5000);
    WebElement w17= driver.findElement(By.id("cc_exp_year"));
    Select s8 = new Select(w17);
    s8.selectByIndex(12);
    Thread.sleep(5000);
    WebElement w18 = driver.findElement(By.name("cc_cvv"));
    w18.sendKeys("3214");  
    Thread.sleep(5000);
    WebElement w19 = driver.findElement(By.name("book_now"));
    w19.click();
    Thread.sleep(5000);
    JavascriptExecutor ex = (JavascriptExecutor) driver;
    Thread.sleep(5000);
    ex.executeScript("window.scroll(0,500)", "");
    Thread.sleep(15000);
    TakesScreenshot ts =(TakesScreenshot) driver;
    File Source =ts.getScreenshotAs(OutputType.FILE);
    File Des = new File("C:\\Users\\acer\\eclipse-workspace\\Selenium\\Screenshot\\Booking confirmation2.png");
    FileUtils.copyFile(Source, Des);
}
}
